#!/bin/env python3

import argparse
import collections
import importlib
import os
import re
import subprocess
import sys



SELFPATH = os.path.dirname(os.path.realpath(sys.argv[0]))



def load_unidecode():
    global unidecode

    path = os.path.join(SELFPATH, "unidecode")
    loader = importlib.machinery.SourceFileLoader("unidecode", path)
    spec = importlib.util.spec_from_file_location("unidecode", loader=loader)
    if spec is None:
        raise ModuleNotFoundError(f"No module named 'unidecode'")

    unidecode = importlib.util.module_from_spec(spec)
    sys.modules["unidecode"] = unidecode
    spec.loader.exec_module(unidecode)



def load_data(path):
    retval = []
    with open(path) as fp:
        for line in fp:
            line = line.split(";")
            codepoint = int(line[0], 16)
            name = line[1]
            if line[1] == "<control>":
                name = line[10]

            yield (name, codepoint)



def match_names(names, strings, regexes):
    strings = [s.upper() for s in strings]
    regexes = [re.compile(r, re.IGNORECASE) for r in regexes]

    args = collections.namedtuple("Args", "normalize")(None)
    first = True
    for name, cp in names:
        if any(s in name for s in strings) or any(r.search(name) for r in regexes):
            unidecode.print_string(args, chr(cp), print_header=first)
            first = False



def main():
    """Main function. Parses the arguments, search the UnicodeData.txt file for
    code points matching the description."""

    parser = argparse.ArgumentParser(description="Search unicode code point "
                                     "matching the description and print its "
                                     "informations.")
    parser.add_argument("stringarg", nargs="?",
                        help="Substring or pattern to look for.")
    parser.add_argument("--unicode-data", "-u", metavar="file",
                        help="Path to UnicodeData.txt to parse and search.")
    parser.add_argument("--regex", "-r", metavar="REGEX", action="append",
                        default=[],
                        help="Search this regular expression. Can be supplied "
                        "multiple times, finds entries matching any pattern.")
    parser.add_argument("--string", "-s", metavar="STRING", action="append",
                        default=[],
                        help="Search this substring. Can be supplied "
                        "multiple times, finds entries matching any string.")

    args = parser.parse_args()

    if not args.regex and not args.string and not args.stringarg:
        print("Must supply at least one search pattern.", file=sys.stderr)
        return 1

    if args.stringarg is not None:
        args.string.append(args.stringarg)

    if args.unicode_data is None:
        args.unicode_data = os.path.join(SELFPATH, "UnicodeData.txt")


    load_unidecode()
    names = load_data(args.unicode_data)
    match_names(names, args.string, args.regex)



if __name__ == "__main__":
    sys.exit(main())
